### ISSUE TITLE
white background is unnecessary

### ISSUE THREAD

**Issue by AngeIII** [wpbakery/visual-composer-starter#112]
The current theme adds `body -> background: #FFF`, this is unnecessary, and can be removed, or should be changeable in the customizer. 

By default, it is white anyway.

**Comment by AngeIII** [comment]
@RaitisSevelis what do you think about this? Actually, it looks weird for example when uses custom CSS option in visual composer and `body { background: red; }` will not work because theme has implicitly set it already.

**Comment by RaitisSevelis** [comment]
@AngeIII yes, agree. With colors, it is an interesting story. There is no option to disable colors right now which is bad. And of course, VC must be able to overwrite it.

**Comment by veidenbaums** [comment]
@AngeIII @RaitisSevelis Just had a look at this, the background color already can be changed via the customizer, and if it's set to #fff in customizer, it won't show up. It is included as inline css in header. 

So I think we can remove the body defined bg color from style css as @AngeIII said at the beginning.

**Comment by RaitisSevelis** [comment]
@veidenbaums sounds good to me

**Comment by RaitisSevelis** [comment]
Decided to correct colors on how they apply, white color must be visible on menu background if space for menu is reserved. For submenu, color (even white) is always visible.
