### ISSUE TITLE
make assets folder with all css/js and sources

### ISSUE THREAD

**Issue by AngeIII** [wpbakery/visual-composer-starter#142]
*This is under discussion* - need to make sure this is not `conflicts` with WordPress theme development standards.

There are few steps to introduce

1. need to make assets folder and move css,js,images,less into it (assets/src/less, assets/src/js, assets/fonts, assets/images)
2. need split minified files into `dist` folder (assets/dist/css, assets/dist/js)
3. need to synchronize the functions.js changes with functions.min.js and check other files.

tasks related, but not affected #61

**Comment by AngeIII** [comment]
@veidenbaums any ideas of that?

**Comment by veidenbaums** [comment]
I don't see anything here that would conflict with WordPress standarts, only thing, that a theme should contain only one `style.css`, if there are two like now, then the Theme Check Plugin, that is used by WordPress.org to check the theme will show a `warning`.

**Comment by AngeIII** [comment]
I just worried, that many themes have structure like:
```
/css
/js
/images
````

**Comment by veidenbaums** [comment]
As I know there aren't any restrictions for that.
