### ISSUE TITLE
Theme Directory Change

### ISSUE THREAD

**Issue by keepkalm** [wpbakery/visual-composer-starter#147]
I don't know if this was thought out, but it does break child themes when the theme directory gets changed.

**Comment by mmihey** [comment]
Hi, That was a maintenance decision. We plan to submit this theme to WordPress.org repository someday and it's required to have the same slug (used for localization) and theme folder name. We don't plan to rename it again.

**Comment by keepkalm** [comment]
No worries, sounds like the correct decision and I suppose it is an easy fix, but a warning might have been the right thing to do there.
