### ISSUE TITLE
"please make sure to install Advanced Custom Fields

### ISSUE THREAD

**Issue by emj-p** [wpbakery/visual-composer-starter#151]
Hi there,

I have ACF PRO installed, but am still getting the nag:
"In order to access full theme options, please make sure to install Advanced Custom Fields"

Is there any way i can remove this?
Thanks

**Comment by AngeIII** [comment]
We will fix the issue in next release. Which version of acf you are using?

**Comment by crstnio** [comment]
I get the recommended plugin warning, too. ACF Pro 5.6.7 is installed.
