### ISSUE TITLE
Compatibility with cache plugin for visual composer

### ISSUE THREAD

**Issue by hailite** [wpbakery/visual-composer-starter#161]
Sorry to paste the issue here. As we can't find any feedback way to visual composer:

Due to nonce used in frontend, please have a look at https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:lscwp:esi_nonce to improve the compatibility with LiteSpeed cache plugin.

Thanks.

**Comment by veidenbaums** [comment]
About this question please contact our support team here: http://support.wpbakery.com/

**Comment by hailite** [comment]
This is not a customer, I am a developer. Your support needs logged in before submit any issue!

If I can do there, I won't come here.
