### ISSUE TITLE
Navbar logo full size on devices less than 768px

### ISSUE THREAD

**Issue by konutis** [wpbakery/visual-composer-starter#162]
If navbar logo original sizes are big -> on mobile devices less than 768px it is full size (no responsiveness).

![screen shot 2017-09-28 at 12 09 09](https://user-images.githubusercontent.com/11874495/30958451-dc576b06-a445-11e7-938d-9ec733f9e90b.png)

**Comment by Jerlec** [comment]
Hi,
I think you should give a max-width to you logotype using CSS. Something like that 
.navbar-brand img {
max-width:140px;
height:auto;
}
It worked for me.

**Comment by peterluu** [comment]
A better solution for better responsiveness would be:
````
img {
	max-width: 100%;
	height: auto;
}

.navbar-brand {
	max-width: 100%;
}
````
This ensures responsive images and the `.navbar-brand` element being responsive also.
