### ISSUE TITLE
In Customizer > Fonts > Body can't change font to Lato, it stays Roboto font after save.

### ISSUE THREAD

**Issue by webprom** [wpbakery/visual-composer-starter#165]
Body font change not saving. Roboto font can't be changed. + it is still requesting all subsets, even while I've specified Latin only. 
Also requested font weights for Lato not loading from google.
I use your child theme.

**Comment by veidenbaums** [comment]
What theme version are you using? Just had a look and it seems to be working fine on my side.

**Comment by webprom** [comment]
latest 1.3 + their child theme

**Comment by fatherb** [comment]
I have the same problem. Tried to change the body font to something else and regardless of what you choose it stays on Roboto. Using latest 1.3 plus the child theme.

**Comment by pietpomp1** [comment]
New here so apologies for the formatting.  Had the same problem and traced it to a typo in class-vct-customizer.php (v 1.3) and looks to still be there on class-visualcomposerstarter-customizer.php (v 2.0.4).

**v1.3**:
`$wp_customize->add_setting( 'vct_fonts_and_style_buttons_font_family', array(
			'default'        => 'Playfair Display',
			'sanitize_callback' => array( $this, 'sanitize_select' ),
		) );`
should be:
`$wp_customize->add_setting( 'vct_fonts_and_style_buttons_font_family', array(
			'default'        => 'Playfair Display',
			'sanitize_callback' => array( $this, 'sanitize_select_google_fonts' ),
		) );`

Sorry can't give the line numbers as mine added extra blank lines.

**Comment by suhiminain** [comment]
@pietpomp1 it line 2110 in class-visualcomposerstarter-customizer.php. Thanks. already solved this problem..

**Comment by veidenbaums** [comment]
@pietpomp1 this was already fixed in the 2.0.4 version before a while.

**Comment by AngeIII** [comment]
#222

**Comment by AngeIII** [comment]
Merged
