### ISSUE TITLE
Customizer Content Area not visible

### ISSUE THREAD

**Issue by andrewpros** [wpbakery/visual-composer-starter#169]
Hi.

There is a bug in customizer where you cant see content area options as they are not properly setup in function register_customize_sections

https://github.com/wpbakery/visual-composer-starter/blob/master/inc/customizer/class-vct-customizer.php#L59

As you can see section vct_content_area is never added thus never visible, i've struggled with this as i was unable to use full width option so i found that is the issue.

**Comment by veidenbaums** [comment]
Duplicate of #199
