### ISSUE TITLE
Header/Footer Scripts failing to save when <script> present

### ISSUE THREAD

**Issue by sweetappleuk** [wpbakery/visual-composer-starter#170]
You cannot use the Customizer -> Header/Footer script for anything but very simple inline javascript as it fails to save any data if a <script> tag is present.

VCT_Customizer::scripts() method should have 'sanitize_callback' => 'wp_strip_all_tags', removed to allow people to save Google Analytics tracking code, etc.

**Comment by veidenbaums** [comment]
Hi!

Header and footer scripts will be removed in next update, as this is plugin theory and required by WordPress.org.

We can suggest using some plugins for this, for example, our Visual Composer Website Builder that will also allow you to add custom scripts.
