### ISSUE TITLE
New version 2.0.4 kills off the widget areas in Footer

### ISSUE THREAD

**Issue by fatherb** [wpbakery/visual-composer-starter#199]
The widget areas in the footer no longer appear after upgrading to 2.0.4 version.

**Comment by veidenbaums** [comment]
Hi!

Do you use a child theme?

**Comment by fatherb** [comment]
Yes, your visual composer starter child theme.

**Comment by veidenbaums** [comment]
Due WordPress org requirements, we needed to update multiple function and action names in the parent theme, so this could cause issues on the child theme, please check your child theme functions and actions and that should solve the issue.

**Comment by veidenbaums** [comment]
Can confirm that this will be fixed in upcoming update.

**Comment by andrewpros** [comment]
thx
