### ISSUE TITLE
Menu Options not visible on Customer Area

### ISSUE THREAD

**Issue by mail2vjj** [wpbakery/visual-composer-starter#202]
When you login via Admin account on Wordpress,menu options are not visible in Customer Area.

**Comment by veidenbaums** [comment]
Hi!

Could you please be more detailed about this, may you can add some screenshot to be more clear?

**Comment by mail2vjj** [comment]
I am using the Customer Area plugin and in its menu I am not able to see the menu if I sign in as an admin or an editor.

If I sign in as a client, then I can see the menu.
It is a theme related issue and the problem is not with Customer Area, as I have tried different themes and they do show the menu, not matter the user profile.

Here are some screenshots, I hope it provides more clarity on the problem.

Thank you,
Vishesh Jain

![admin](https://user-images.githubusercontent.com/39300211/43395661-716ea760-941c-11e8-9c9e-c4f1765b0f51.jpg)
![editor](https://user-images.githubusercontent.com/39300211/43395662-71b27a12-941c-11e8-9b4a-5eba2b458026.jpg)
![test client](https://user-images.githubusercontent.com/39300211/43395663-71f4b800-941c-11e8-808f-8e58e9775e61.jpg)

**Comment by veidenbaums** [comment]
Just had a look and it works fine, maybe you have some custom CSS somewhere? 
Also, this plugin seems to have issues with PHP 7, needed to create a patch for it to get it to work,

![image](https://user-images.githubusercontent.com/28038713/43568748-204c422e-963e-11e8-81e0-0728fe6d2144.png)
