### ISSUE TITLE
Sticky Header option not showing full list of dropdown menu items

### ISSUE THREAD

**Issue by nomadmedia** [wpbakery/visual-composer-starter#203]
If I activate the sticky menus and scroll down a list of items, list stops at the bottom of the browser window missing any remaining menu items in the list. Wherever browser screen is fully extended vertically, the list will scroll to that point. (I am viewing on a 15 inch macbook pro with screen resolution 1400x900 and Firefox, latest versions of VC starter & VC Website Builder. This bug applies to all other desktop/laptop machines with similar resolutions and various browsers.) 

I can introduce a scroll bar via css to overcome this limitation but fixing the menu scrolling issue in the next update would be a major help. Perhaps adding a dropdown icon that appears at the bottom of the visible sub-menu area to indicate 'more  menu items below' would be a more elegant fix.

**Comment by konutis** [comment]
Fixed Pull Request #207
