### ISSUE TITLE
Built style.css instead of included

### ISSUE THREAD

**Issue by szepeviktor** [wpbakery/visual-composer-starter#61]
Please consider including the less build script that includes the WP theme meta headers and outputs the minified style.css at the standard (`/style.css`) location.

Developers using this repo should be able to run nodejs.

A release version (.zip) may contain the CSS output and **exclude** less files.

**Comment by AngeIII** [comment]
Actually, we have less folder and not at compilation via `lessc` it compiles into styles.css, next stage is autoprefixer and gulp/grunt.

**Comment by AngeIII** [comment]
due to we use `css/styles.css` we need to change that to included one `/style.css`
