### ISSUE TITLE
Prefixer for less

### ISSUE THREAD

**Issue by szepeviktor** [wpbakery/visual-composer-starter#67]
Please consider using a vendor prefixer mixin for less.
https://github.com/wpbakery/visual-composer-theme/blob/master/css/slick.css#L6-L11

**Comment by szepeviktor** [comment]
https://github.com/wpbakery/visual-composer-theme/blob/master/css/slick.css#L32-L36

**Comment by csoutham** [comment]
I'd be happy to build out a Gulp based workflow here? With sourcemapping, browsersync etc

**Comment by AngeIII** [comment]
@csoutham pull requested is appreciated ;)

**Comment by AngeIII** [comment]
As a theme developer we want to have styles/src directory which will contain all required files like sass or less, then via some tool (gulp or grunt actually) be able to compile them into styles.css/styles.min.css with appending the prefixes via autoprefixer plugin.

Any pull requests will be great.
