### ISSUE TITLE
WOFF2

### ISSUE THREAD

**Issue by szepeviktor** [wpbakery/visual-composer-starter#68]
Please consider adding the modern font format for `visual-composer-starter-font`

**Comment by AngeIII** [comment]
already are fonts/visual-composer-starter-font.woff

**Comment by szepeviktor** [comment]
Please be aware that it is not woff2.

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by AngeIII** [comment]
¯\_(ツ)_/¯ 
my mistake, @szepeviktor thanks:)
