### ISSUE TITLE
Compatibility with Woo Commerce

### ISSUE THREAD

**Issue by RaitisSevelis** [wpbakery/visual-composer-starter#93]
As a user, I want to Starter theme to be compatible with Woo Commerce. Theme must be Woo Commerce ready in terms of functionality and design (will be provided)

Documentation: Documentation: https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/?utm_source=notice&utm_medium=product&utm_content=themecompatibility&utm_campaign=woocommerceplugin

**Comment by keepkalm** [comment]
Here's my woocommerce.php file, add it to your child theme folder and it will work just fine. 

Here's the link for my [WooCommerce Shop](http://seobandwagon.com/shop/) using Visual Composer.

Rename the file, I can't upload a php to github. 
[woocommerce.txt](https://github.com/wpbakery/visual-composer-starter/files/1020428/woocommerce.txt)

**Comment by veidenbaums** [comment]
Added compatibility in #224
